### ISSUE TITLE
 "no such file or directory " pointcloud 

### ISSUE THREAD

**Issue by Gardlin** [Xharlie/pointnerf#3]
Hello .  Thanks for your amazing work.

However ,  When I  run bash/dev_scripts/hotdog_test.sh ， it goes with  FileNotFoundError ,in  line 248  load_blender_cloud  load_blender_cloud.py ,  where is the pointcloud  saved/dumped  in your scripts .  I can't find  the this.

**Comment by Xharlie** [comment]
I'm confused since it shouldn't go there with the default value load_points=0,  did you change the script? 
The saved point cloud is included in the checkpoint files, since they are also subject to optimization. 

Please let me know if you have changed the script that cause this error, you can git diff the bash/dev_scripts/hotdog_test.sh
It should NOT get to line 248.

**Comment by Kathygg90** [comment]
thanks for your great job! I have the same problem when I run "bash dev_scripts/w_n360/ship_test.sh". It goes with FileNotFoundError in line 118 of load_blender.py. My datapath is pointnerf/data_src/nerf/nerf_synthetic/ship，and it includes 3 .json files and 3 folders containing some .png pictures.

Could you please tell me where the "point_path" is?  Thank you~

**Comment by Xharlie** [comment]
let's discuss in issue #7

**Comment by Xharlie** [comment]
let's discuss in issue #7
